name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 3.3.4
  EXPORT_NAME: TestCI

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: cd ..
        run: ls
      # - name: Setup
      #   run: |
      #     mkdir -v -p ~/.local/share/godot/templates
      #     mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      # - name: Windows Build
      #   run: |
      #     mkdir -v -p build/windows
      #     ls
      #     cd $EXPORT_NAME
      #     godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: windows
      #     path: build/windows
