on: [workflow_dispatch]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dawidd6/action-download-artifact@v2.17.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: deploy.yml
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
