on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - id: tag_version
        uses: dawidd6/action-download-artifact@v2.17.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: deploy.yml
          workflow_conclusion: success
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
